### ISSUE TITLE
how to use this ?

### ISSUE THREAD

**Issue by omgbox** [trueromanus/TorrentStream#6]
can you please make tutorial how to use

**Comment by trueromanus** [comment]
Hi, you can download binary from releases for your OS.

First of all need to adjust (if required) port and download path.

### Application port
The default application port is 5082. You can change the port by defining the `WEB_PORT` environment variable.

### Downloaded path or where are downloaded in torrent client files will be stored
The files are stored in the `Downloads` folder relative to the folder where the application is located. You can change the main path by defining the `DOWNLOAD_PATH` environment variable.

### Open in player
After it you can use it from players supporting HTTP Streaming like VLC.  
Example for VLC:
- Open VLC app.
- Open menu Media > Open URL
- Fill field URL to `http://127.0.0.1:<port what you adjusted before>/online?index=0&id=1&path=https://path_to_torrent_file/sample.torrent` (see full description parameters and other methods in REST API below)
- Click play (dependence from count peers on torrent streaming of video can be starting not immediately, but with some delay and it ok)
- Watch video from torrent :)

If you want use local torrent file need to use file protocol like this: `file://usr/path_torrent_file/test.torrent`
On windows protocol will be `file:///` (3 slashes)

`REST API`
/online?index=X&id=Y&path=Z
X is the index of the file in the torrent where downloading and streaming will begin
Y - a numeric value used as an identifier for external sources.
Z - full URL for downloading the torrent file (not a magnet link! supported only torrent file)
The response (if everything was successful) will be redirected to the link for streaming the video file (the index of which is specified in the index parameter). Those. in the player, when you put this link (/online), inside which the torrent file will be downloaded, and start downloading it in the external client, and as a result, you will be redirected to the streaming link.

/fulldownload?id=Y&path=Z
Y - a numeric value used as an identifier for external sources.
Z - full URL for downloading the torrent file (not a magnet link specifically to the torrent file)
The answer is empty. If everything is transferred correctly, the torrent file will be downloaded and the downloading of its content on the client will begin.

/torrents
The response contains data about current torrents in JSON format.
Sample answer:

[
    {
      "Identifier": 1,
      "DownloadPath": "C:/blablabla/path",
      "AllDownloaded": false,
      "Files": [
        {
          "Loaded": false,
          "Percentage of completion": 80,
          "DownloadedPath": "C:/blablabla/path/file.mp4"
        }
      ]
    }
]
/clear all
The answer is empty. Removes all files and torrents available to the client.

/clearonlytorrent?path=X
X is the URL of the torrent file previously transferred via /online or /fulldownload.
The answer is empty. Removes the torrent from the client, already downloaded files in the file system.

/cleartorrentanddata?path=X
X is the URL of the torrent file previously transferred via /online or /fulldownload.
The answer is empty. Removes the torrent from the client and downloaded files from the file system

**Comment by trueromanus** [comment]
If you have another question please feel free reopen this issue.
